file:///media/disk/tr/bigfile.000 file:///media/disk/tr/bigfile.001 file:///media/disk/tr/bigfile.002 file:///media/disk/tr/bigfile.003 file:///media/disk/tr/bigfile.004 file:///media/disk/tr/bigfile.005
regenerate bindings because of errors like:

plugins/behaviourlayer/python/blcel.cpp: In function ‘PyObject* _wrap_iCelPropertyClass_IsPropertyReadOnly(PyObject*, PyObject*)’:
plugins/behaviourlayer/python/blcel.cpp:31826: error: ‘StringID’ is not a member of ‘CS’
plugins/behaviourlayer/python/blcel.cpp:31826: error: ‘StringID’ is not a member of ‘CS’
plugins/behaviourlayer/python/blcel.cpp:31826: error: ‘StringSetTag’ is not a member of ‘CS’
plugins/behaviourlayer/python/blcel.cpp:31826: error: template argument 1 is invalid
plugins/behaviourlayer/python/blcel.cpp:31826: error: expected unqualified-id before ‘>’ token
plugins/behaviourlayer/python/blcel.cpp:31840: error: ‘arg2’ was not declared in this scope
plugins/behaviourlayer/python/blcel.cpp:31842: error: ‘arg2’ was not declared in this scope
plugins/behaviourlayer/python/blcel.cpp: In function ‘PyObject* _wrap_iCelPropertyClass_GetPropertyLong(PyObject*, PyObject*)’:
plugins/behaviourlayer/python/blcel.cpp:31853: error: ‘StringID’ is not a member of ‘CS’
plugins/behaviourlayer/python/blcel.cpp:31853: error: ‘StringID’ is not a member of ‘CS’
plugins/behaviourlayer/python/blcel.cpp:31853: error: ‘StringSetTag’ is not a member of ‘CS’
plugins/behaviourlayer/python/blcel.cpp:31853: error: template argument 1 is invalid
plugins/behaviourlayer/python/blcel.cpp:31853: error: expected unqualified-id before ‘>’ token
plugins/behaviourlayer/python/blcel.cpp:31867: error: ‘arg2’ was not declared in this scope
plugins/behaviourlayer/python/blcel.cpp:31869: error: ‘arg2’ was not declared in this scope
plugins/behaviourlayer/python/blcel.cpp: In function ‘PyObject* _wrap_iCelPropertyClass_GetPropertyFloat(PyObject*, PyObject*)’:
plugins/behaviourlayer/python/blcel.cpp:31880: error: ‘StringID’ is not a member of ‘CS’
plugins/behaviourlayer/python/blcel.cpp:31880: error: ‘StringID’ is not a member of ‘CS’
plugins/behaviourlayer/python/blcel.cpp:31880: error: ‘StringSetTag’ is not a member of ‘CS’
plugins/behaviourlayer/python/blcel.cpp:31880: error: template argument 1 is invalid
plugins/behaviourlayer/python/blcel.cpp:31880: error: expected unqualified-id before ‘>’ token
plugins/behaviourlayer/python/blcel.cpp:31894: error: ‘arg2’ was not declared in this scope
plugins/behaviourlayer/python/blcel.cpp:31896: error: ‘arg2’ was not declared in this scope
plugins/behaviourlayer/python/blcel.cpp: In function ‘PyObject* _wrap_iCelPropertyClass_GetPropertyBool(PyObject*, PyObject*)’: